---
title: "Untitled"
output: word_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
load("../model/insamp_res_list.RData")
load("../model/outsamp_res_list.RData")
kospi <- read_csv("../data/processed/kospi.csv")
```

```{r}
method_mean <- function(x) {
  n <- nrow(x)
  y <- 
    x %>% 
    select(cumsum, sd, info_r) %>% 
    as.matrix() %>% 
    matrix(nrow = 2) %>% 
    apply(2, mean) %>% 
    matrix(nrow = 0.5 * n) %>% 
    round(3) %>% 
    as_tibble() %>% 
    setNames(c("cumsum", "sd", "info_r"))
  x %>% 
    select(with, n_time) %>% 
    distinct() %>% 
    bind_cols(y)
}


n <- nrow(insamp_res_list[[1]]$summary)
summ_mat <- matrix(0, nrow = n, ncol = 3)

for (i in seq_along(insamp_res_list)) {
  summ_mat <- summ_mat + 
    insamp_res_list[[i]]$summary %>% 
    select(cumsum, sd, info_r) %>% 
    as.matrix()
}

summ_mat <- 
  (summ_mat / length(insamp_res_list)) %>% 
  as_tibble() %>% 
  setNames(c("cumsum", "sd", "info_r"))

insamp_summ <- 
  insamp_res_list[[1]]$summary %>% 
  select(with, n_time, method) %>% 
  bind_cols(summ_mat) %>% 
  method_mean() %>% 
  mutate(rank = min_rank(-info_r))

outsamp_summ <- 
  outsamp_res$summary %>% 
  method_mean() %>% 
  mutate(rank = min_rank(-info_r))
```

```{r}
n <- nrow(insamp_res_list[[1]]$return)
ret_mat <- matrix(0, nrow = n, ncol = 3)

for (i in seq_along(insamp_res_list)) {
  ret_mat <- ret_mat +
    insamp_res_list[[i]]$return %>% 
    select(kospi, factors_8_GMV, factors_8_Tangency) %>% 
    as.matrix()
}

ret_mat <- 
  (ret_mat / length(insamp_res_list)) %>% 
  apply(2, cumsum) %>% 
  as_tibble() %>% 
  setNames(c("kospi", "GMV", "Tangency"))

insamp_ret <- 
  tibble(time = str_c("Q", 1:n)) %>% 
  mutate(time = factor(time, levels=time)) %>% 
  bind_cols(ret_mat)

outsamp_ret <- 
  outsamp_res$return %>% 
  select(time, kospi, factors_8_GMV, factors_8_Tangency) %>% 
  setNames(c("time", "kospi", "GMV", "Tangency"))
outsamp_ret[2:4] <- lapply(outsamp_ret[2:4], cumsum)

insamp_cumret_plot <- 
  insamp_ret %>% 
  gather(key = asset, value = logret, 2:4) %>% 
  mutate(asset  =  factor(asset, levels = c("Tangency", "GMV", "kospi"))) %>% 
  ggplot(aes(x = time, y = logret, group = asset, col = asset)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_point() +
  geom_line() +
  scale_color_discrete(name = NULL, labels = c("Tangency", "GMV", "KOSPI")) +
  xlab("Time") + ylab("Cumulative log return") +
  theme_bw()

outsamp_cumret_plot <- 
  outsamp_ret %>% 
  gather(key = asset, value = logret, 2:4) %>% 
  mutate(asset = factor(asset, levels = c("Tangency", "GMV", "kospi"))) %>% 
  ggplot(aes(x = time, y = logret, group = asset, col = asset)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_point() +
  geom_line() +
  scale_color_discrete(name = NULL, labels = c("Tangency", "GMV", "KOSPI")) +
  xlab("Time") + ylab("Cumulative log return") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = .5))
```

## In-sample

```{r}
knitr::kable(insamp_summ)
insamp_cumret_plot
```

## Out-sample

```{r}
knitr::kable(outsamp_summ)
outsamp_cumret_plot
```
